export const CARDS = [
  {
    id: 0,
    image: "/gartner.avif",
    name: "Gartner",
    from: "12 Jun, 2023",
    to: "present",
    position: "Software Engineer 2",
    location: "Gurugram | India",
    responsibilities: [
      "Accountable for migrating the serverless codebase to a Next.js monorepo, enhancing maintainability and improving core web vitals by approximately 20%.",
      "Led the implementation of 8 experimental features over 2 months, 4 of which were successful.",
      "Developed custom fields in Contentful to enhance the type of content on the blog webapp. ",
      "Managed Datadog and FullStory, and conducted weekly bug bashes, reducing errors by 99% over a quarter.",
    ],
  },
  {
    id: 1,
    image: "/thoughtworks.avif",
    name: "Thoughtworks",
    from: "25 Apr, 2022",
    to: "09 Jun, 2023",
    position: "UI Developer - Consultant",
    location: "Gurugram | India",
    responsibilities: [
      "Worked with Micro-frontends (using Module Federation) written in React, leveraging the API contract to create various forms for banking services, thereby eliminating the need to develop each form individually.",
      "Championed TDD practices and reusable frontend components to improve code quality and team standards.",
      "Took ownership of setting up a generic project boilerplate for micro-frontends, accelerating onboarding by approximately 10 days.",
    ],
  },
  {
    id: 2,
    image: "/geektrust.avif",
    name: "Geektrust",
    from: "8 Sep, 2021",
    to: "22 Apr, 2022",
    position: "Applications Developer",
    location: "Gurugram | India",
    responsibilities: [
      "Answerable for developing client-specific proof-of-concept solutions using React.js.",
      "Took ownership of integrating a React widget with Microsoft Dynamics 365 to enable realtime CRM data interaction.Took ownership of integrating a React widget with Microsoft Dynamics 365 to enable realtime CRM data interaction.",
    ],
  },
  {
    id: 3,
    image: "/infosys.avif",
    name: "Infosys",
    from: "5 Aug, 2019",
    to: "6 Sep, 2021",
    position: "Systems Engineer",
    location: "Chandigarh | India",
    responsibilities: [
      "Developed a serverless web application using React, incorporating an upload feature that allowed users to submit data. This data was then processed by a machine learning algorithm hosted on AWS Sagemaker.",
      "Used AWS to deploy the serverless application, leveraging AWS Lambda to create and manage the required API endpoints.",
    ],
  },
];
