export const CARDS = [
  {
    id: 0,
    image: "/gartner.avif",
    name: "Gartner",
    from: "12 Jun, 2023",
    to: "24 Sept, 2025",
    position: "Software Engineer 2",
    location: "Gurugram | India",
    responsibilities: [
      "Accountable for migration and optimization of serverless codebase to a Next.js monorepo, enhancing maintainability and improving core web vitals by approximately 20%",
      "Led the implementation of 8 experimental features over 2 months, 4 of which were successful",
      "Developed an innovative solution to support tokens for two design systems within a single web application, reducing the deployment timeline for the revamped app from 12 months to just 3 months",
      "Managed Datadog and FullStory for auditing and benchmarking, and conducted weekly bug bashes, reducing errors by 99% over the course of a quarter",
      "Collaborated with cross-functional teams to discuss integration strategies and build solutions quickly while maintaining high-quality standards",
    ],
  },
  {
    id: 1,
    image: "/thoughtworks.avif",
    name: "Thoughtworks",
    from: "25 Apr, 2022",
    to: "09 Jun, 2023",
    position: "UI Developer – Consultant",
    location: "Gurugram | India",
    responsibilities: [
      "Worked with micro-frontends (using Module Federation) written in React, leveraging the API contract to create dedicated forms for banking services by simple data fetching via GraphQL query, thereby eliminating the need to develop each form individually",
      "Championed Test-Driven Development practices and reusable frontend components to improve code quality and team standards",
      "Took ownership of setting up a generic project boilerplate for micro-frontends, accelerating onboarding by approximately 10 days, thus increasing overall productivity",
      "Participated in and received code reviews to iterate on and develop a robust, high-quality polished solution",
    ],
  },
  {
    id: 2,
    image: "/geektrust.avif",
    name: "Thoughtworks",
    subText: "via Geektrust",
    from: "08 Sep, 2021",
    to: "22 Apr, 2022",
    position: "Application Developer",
    location: "Gurugram | India",
    responsibilities: [
      "Responsible for developing client-specific proof-of-concept solutions using React.js",
      "Took ownership of Integrating a React widget with Microsoft Dynamics 365 dashboard to enable real-time CRM data interaction",
      "Collaborated closely with design and product teams to align on requirements and deliver seamless solutions",
    ],
  },
  {
    id: 3,
    image: "/infosys.avif",
    name: "Infosys",
    from: "05 Aug, 2019",
    to: "06 Sep, 2021",
    position: "Systems Engineer",
    location: "Chandigarh | India",
    responsibilities: [
      "Developed serverless single page applications using React, one of which, incorporated an upload feature that allowed users to submit data. This data was then processed by a machine learning algorithm hosted on AWS Sagemaker",
      "Used AWS to deploy the serverless application, leveraging AWS Lambda to create and manage the required API endpoints",
    ],
  },
];
