export const CARDS = [
  {
    id: 1,
    color: "#000000",
    image: "./infosys.avif",
    name: "Infosys",
    from: "5 Aug, 2019",
    to: "6 Sep, 2021",
    position: "Systems Engineer",
    location: "Chandigarh | India",
    responsibilities: [
      "Developed serverless web applications using React, incorporating an upload feature that allowed users to submit data. This data was then processed by a machine learning algorithm hosted on AWS.",
      "Utilized AWS to deploy the serverless application, leveraging AWS Lambda to create and manage the necessary API endpoints.",
    ],
  },
  {
    id: 2,
    color: "#66ff66",
    image: "./geektrust.avif",
    name: "Geektrust",
    from: "8 Sep, 2021",
    to: "22 Apr, 2022",
    position: "Applications Developer",
    location: "Bangalore | India",
    responsibilities: [
      "Developed proof-of-concept solutions tailored to address the unique needs and objectives of the client.",
      "Integrated a react app widget with Microsoft Dynamics 365.",
    ],
  },
  {
    id: 3,
    color: "#6666ff",
    image: "./thoughtworks.avif",
    name: "Thoughtworks",
    from: "25 Apr, 2022",
    to: "09 Jun, 2023",
    position: "UI Developer - Consultant",
    location: "Gurugram | India",
    responsibilities: [
      "Worked with a Form Builder React application which uses the API contract to create different forms for different banking services while using micro frontends with Module Federation for separation of interests.",
      "Continuously learned and adapted to new technologies, utilizing the appropriate tech stack based on project requirements and opportunities.",
      "Adhered to Test-Driven Development (TDD) practices, writing clean, reusable frontend components.",
      "Established standardized boilerplate setup which was used to set up other micro-frontend boilerplates in the same project.",
    ],
  },
  {
    id: 4,
    color: "#ffff66",
    image: "./gartner.avif",
    name: "Gartner",
    from: "12 Jun, 2023",
    to: "present",
    position: "Software Engineer 2",
    location: "Gurugram | India",
    responsibilities: [
      "Migrated the serverless codebase to a Next.js monorepo, streamlining development and enhancing maintainability.",
      "Contributed to the development of a high-impact application that generates the majority of revenue for the business unit.",
      "Led A/B experiments using LaunchDarkly to assess feature performance and launch the highest-performing variants.",
      "Utilized Contentful to design and implement dynamic, data-driven blog pages for easy content management and updates.",
      "Leveraged monitoring tools like Datadog and FullStory to track, analyze, and optimize the performance of newly released features.",
    ],
  },
];
