import type { Metadata } from "next";
import "./globals.css";
import "./neon.css";
import {
  Luckiest_Guy,
  Noto_Color_Emoji,
  Montserrat_Alternates,
  Overpass,
} from "next/font/google";
import React from "react";

const meddon = Luckiest_Guy({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-meddon",
});

const colorEmoji = Noto_Color_Emoji({
  weight: ["400"],
  subsets: ["emoji"],
  variable: "--font-noto-color-emoji",
});

const rancho = Montserrat_Alternates({
  weight: ["300"],
  subsets: ["latin"],
  variable: "--font-rancho",
});
const biryani = Overpass({
  weight: ["300"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-biryani",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${meddon.variable} ${colorEmoji.variable} ${rancho.variable} ${biryani.variable} bg-theme-ivory bg-theme-grainy text-theme-black`}
      >
        {children}
      </body>
    </html>
  );
}
