import type { Metadata } from "next";
import "./globals.css";
import BackgroundLayout from "../Components/BackgroundLayout.tsx";
import { Montserrat } from "next/font/google";
import React from "react";

import gsap from "gsap";
import { ScrollTrigger } from "gsap/all";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  gsap.registerPlugin(ScrollTrigger);

  return (
    <html lang="en">
      <body className={"h-[6000px]   " + montserrat.className}>
        <BackgroundLayout>{children}</BackgroundLayout>
      </body>
    </html>
  );
}
